# Generated by Django 2.1 on 2019-10-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_auto_20191005_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='candidate_id',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='poll_id',
            new_name='poll',
        ),
    ]
